### PR TITLE
Fixing typo for Spot::Ticker24hr in api.rs

### PR DESCRIPTION
**Pull request by nopbit**
Added "r" letter at the end of api address. With this fix, it is not giving 404 error anymore.

### CODE REVIEW

**Comment by dorak88783** [comment]
Thanks for noticing and opening the PR! 

Your build currently fails because the test code also has the same typo. If you could also fix the typo in https://github.com/wisespace-io/binance-rs/blob/master/tests/market_tests.rs , then likely the build will work.

**Comment by nopbit** [comment]
Thanks, i updated test file also and merged the patches. Best regards

**Comment by dorak88783** [comment]
@wisespace-io It seems you now have to manually approve the workflow for new contributors to it will do the cargo build & test.

**Comment by nopbit** [comment]
I wanted to merge my patch-1 and patch-2 but it is now saying " 1 workflow awaiting approval
First-time contributors need a maintainer to approve running workflows. Learn more. " I can close this request and create new one.

**Comment by wisespace-io** [comment]
@dorak88783 @nopbit Sorry, for the delay. I approved the workflow. Anything else missing?

**Comment by dorak88783** [comment]
Ah, there are two test cases that refer to this end point. It fails in `get_all_24h_price_stats`, this one also needs to be updated.

**Comment by nopbit** [comment]
To be honest i have no idea why it is giving error on test. i will check it on local copy

**Comment by dorak88783** [comment]
Search https://github.com/wisespace-io/binance-rs/blob/master/tests/market_tests.rs for `/api/v3/ticker/24h`, you'll find two locations, and you already fixed one.

You can indeed run `cargo test` locally, it should pass before you push your commits.

**Comment by nopbit** [comment]
Thanks, this time test passed on local copy. Could you please approve it?

**Pull request merged**
