### PR TITLE
Revert "Update libraries"

### PR DESCRIPTION
**Pull request by ppamorim**
Please revert these changes, they are causing the project to not compile.

### CODE REVIEW

**Comment by wisespace-io** [comment]
@ppamorim It does not fix the build yet. Please always run "cargo clippy -- -D warnings" and check the build status in Travis 
https://travis-ci.org/github/wisespace-io/binance-rs/builds/765022593

I have to add a workflow here to make clear when the building is failing, but you can check travis status in the meanwhile

**Comment by dorak88783** [comment]
@wisespace-io : I don't have experience with Travis, but if you are okay with switching to github actions then I can help to set it up. But maybe it's easy to enable with Travis as well :).

**Comment by wisespace-io** [comment]
@dorak88783 if you know how to do with github actions, it would be great. I see that some rust projects switched to Github actions, see example https://github.com/seanmonstar/reqwest/blob/master/.github/workflows/ci.yml

**Comment by ppamorim** [comment]
@wisespace-io @dorak88783 Fixed.

**Pull request merged**
