### PR TITLE
Implement open_interest_statistics

### PR DESCRIPTION
**Pull request by siegfried**

### CODE REVIEW

**Comment by siegfried** [comment]
I'm stuck in creating [open interest statistics API](https://binance-docs.github.io/apidocs/futures/en/#open-interest-statistics). A strange error happened. Could you help to take a look how to fix this? Thanks. @wisespace-io 

```
$cargo test --test futures_market_test

running 1 test
test tests::open_interest_statistics ... FAILED

failures:

---- tests::open_interest_statistics stdout ----
thread 'tests::open_interest_statistics' panicked at 'called `Result::unwrap()` on an `Err` value: Error(ReqError(reqwest::Error { kind: Decode, source: Error("invalid type: integer `1638455400000`, expected a string", line: 1, column: 126) }), State { next_error: None, backtrace: InternalBacktrace })', tests/futures_market_test.rs:22:100
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::open_interest_statistics

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.55s

error: test failed, to rerun pass '--test futures_market_test'
```

**Comment by wisespace-io** [comment]
@siegfried there are some mistakes, but also Binance documentation does not match the data returned.

`    match market.open_interest_statistics("BTCUSDT", "5m", 10, None, None) {
        Ok(answer) => println!("Open interest: {:?}", answer),
        Err(e) => println!("Error: {}", e),
    }`

Add to examples/binance_futures_endpoint.rs and you will see that timestamp is an integer, not a string.

**Comment by siegfried** [comment]
Updated and it passed the test. Thanks for your help. Please review. @wisespace-io

**Comment by siegfried** [comment]
I removed the extra field to pass the check.

```
error: field is never read: `extra`
94
  --> src/errors.rs:11:5
95
   |
96
11 |     extra: HashMap<String, Value>,
97
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
98
   |
99
   = note: `-D dead-code` implied by `-D warnings`
```

**Comment by wisespace-io** [comment]
@siegfried thank you for the fixes and the new feature.

**Pull request merged**
