### PR TITLE
add more endpoints: /fapi/v1/allOrders, /fapi/v1/userTrades, /sapi/v1/futures/transfer

### PR DESCRIPTION
**Pull request by Y0h4n3s**

### CODE REVIEW

**Comment by wisespace-io** [comment]
@Y0h4n3s could you fix the conflicts?

**Comment by Y0h4n3s** [comment]
> @Y0h4n3s could you fix the conflicts?

fixed

**Comment by Y0h4n3s** [comment]
fixed the errors you can merge

**Comment by wisespace-io** [comment]
@Y0h4n3s almost, it still breaks due a lint error. Run cargo clippy, the error below:

```
error: use of `ok_or` followed by a function call
   --> src/model.rs:971:10
    |
971 |         .ok_or(ErrorKind::KlineValueMissingError(index, name))?
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `ok_or_else(|| ErrorKind::KlineValueMissingError(index, name))`
```

**Pull request merged**
