### PR TITLE
Futures websocket API

### PR DESCRIPTION
**Pull request by ppamorim**
[DO NOT MERGE]

Hi,

In this PR we will add the websocket client for the futures API. @wisespace-io Could you please verify or list me what structs are required for this new API? I don't understand their API documentation well compared to the current API in the spot websocket API.

This PR is still under development.

### CODE REVIEW

**Comment by wisespace-io** [comment]
@lasys  In which events are you interested to subscribe? @ppamorim  is working on Futures Websockets support

**Comment by dorak88783** [comment]
@ppamorim  do you still want to finish this? I could start to look into it as well.

I agree the futures API documentation isn't that great. It's also confusing since binance has the USDT-based futures (the original futures) and the COIN-M futures (which seem to be added later), leading to a poor API design in general.

**Comment by ppamorim** [comment]
Please do. I'm stuck. ☹️

**Comment by dorak88783** [comment]
I have a first endpoint working (https://github.com/dorak88783/binance-rs/tree/add_futures_websockets) but I'll need a bit more time to organize everything into a nice API.

**Comment by dorak88783** [comment]
Continued in https://github.com/wisespace-io/binance-rs/pull/124.

**Pull request closed without merging**
