### PR TITLE
Add futures websockets

### PR DESCRIPTION
**Pull request by dorak88783**
Add support for future websockets: implemented the USD-M and COIN-M endpoints; vanilla options are not implemented yet.

There is an example that shows their working, but it depends on the uptime of the binance servers, so I didn't make this into a real test. Real tests (with a mocked) server would be nice. Also documentation is not 100% complete.

### CODE REVIEW

**Comment by wisespace-io** [comment]
@dorak88783 Really nice job here. It is a great start as other contributors will learn from your effort to decipher the Binance Futures API.

**Comment by dorak88783** [comment]
I realize I still have to update the `Config` struct to have the proper default ws host, so please don't merge yet.

**Comment by foonsun** [comment]
merge

**Comment by wisespace-io** [comment]
@dorak88783 any progress?

**Comment by dorak88783** [comment]
Sorry, didn't have time due to personal stuff, don't think I'll have time in the next weeks. If I want to take https://github.com/wisespace-io/binance-rs/issues/125 into account it'll be a major (breaking) change with respect to the current PR.

Feel free to merge as-is or decline. You can always already use this with

    [dependencies]
    binance = { git = "https://github.com/dorak88783/binance-rs.git", branch = "add_futures_websockets" }

**Comment by wisespace-io** [comment]
@dorak88783 I thought about it and I decided to merge it. I will add a note in the README regarding upcoming breaking changes in the Futures API.

**Pull request merged**
